Messages:
  Incorrect-Args: '&cIncorrect args! Try &a<suggestion>'
  Never-Joined: '&c<player> has never joined before! You cannot punish them!'
  Not-Online: '&c<player> is not online! You cannot kick them!'
  Banned: '&aYou have &6banned &a<player>'
  IP-Banned: '&aYou have &6ip-banned &a<player>'
  Ban-Display: '&cYou have been permanently banned for &6<reason>'
  Temp-Banned: '&aYou have &6temp-banned &a<player> for <time>'
  Temp-Ban-Display: '&cYou are temporarily banned until &6<time> &cfor &6<reason>'
  Muted: '&aYou have &6muted &a<player>'
  Mute-Display: '&cYou are muted for &6<reason>'
  Temp-Muted: '&aYou have &6muted &a<player> for <time>'
  Temp-Mute-Display: '&cYou are muted until &6<time> &cfor &6<reason>'
  Kicked: '&aYou have &6kicked &a<player>'
  Kick-Display: '&cYou have been kicked for &6<reason>'
  No-Permission: '&cInsufficient permissions.'
  Invalid-Duration: '&cInvalid duration! Use formats like 1d, 2h30m, etc.'