name: Punishments
api-version: 1.21
version: ${project.version}
author: Dartanboy
main: me.dartanboy.punishments.Punishments
commands:
  ban:
    description: Ban a player permanently
    usage: /<command>
  tempban:
    description: Ban a player temporarily
    usage: /<command>
  mute:
    description: Mute a player permanently
    usage: /<command>
  tempmute:
    description: Mute a player temporarily
    usage: /<command>
  kick:
    description: Kick a player
    usage: /<command>
  banip:
    description: Ban a player and their IP permanently
    usage: /<command>
  unmute:
    description: Unmute a permanently muted player or end their temp mute
    usage: /<command>
  unban:
    description: Unban a permanently banned player or end their temp ban
    usage: /<command>
  history:
    description: View punishment history of a player
    usage: /<command>