name: Punishments
api-version: 1.21
version: ${project.version}
author: Dartanboy
main: me.dartanboy.punishments.Punishments
commands:
  ban:
    description: Ban a player permanently
    usage: /<command>
  tempban:
    description: Ban a player temporarily
    usage: /<command>
  mute:
    description: Mute a player permanently
    usage: /<command>
  tempmute:
    description: Mute a player temporarily
    usage: /<command>
  kick:
    description: Kick a player
    usage: /<command>
  banip:
    description: Ban a player and their IP permanently
    usage: /<command>